# Auto-extracted from src/utils/inline-linker.ts
MONEY_LINKS = [
    ('credit repair companies', '/best/best-credit-repair-companies/'),
    ('credit repair services', '/best/best-credit-repair-companies/'),
    ('debt relief companies', '/best/best-debt-relief-companies/'),
    ('debt relief programs', '/best/best-debt-relief-companies/'),
    ('personal loans for bad credit', '/best/best-personal-loans-bad-credit/'),
    ('personal loan lenders', '/best/best-personal-loan-lenders/'),
    ('debt consolidation loans', '/best/best-debt-consolidation-loans/'),
    ('debt consolidation', '/best/best-debt-consolidation-loans/'),
    ('credit builder loans', '/best/best-credit-builder-loans/'),
    ('secured credit cards', '/best/best-secured-credit-cards/'),
    ('credit monitoring services', '/best/best-credit-monitoring-services/'),
    ('credit monitoring', '/best/best-credit-monitoring-services/'),
    ('cash advance apps', '/best/best-cash-advance-apps/'),
    ('payday loan alternatives', '/best/best-payday-loan-alternatives/'),
    ('credit counseling', '/best/best-credit-counseling-agencies/'),
    ('identity theft protection', '/best/best-identity-theft-protection/'),
    ('rent reporting', '/best/best-rent-reporting-services/'),
    ('credit score simulator', '/tools/credit-score-simulator/'),
    ('borrowing power', '/tools/borrowing-power-quiz/'),
    ('debt payoff calculator', '/tools/debt-payoff-calculator/'),
    ('credit repair', '/categories/credit-repair/'),
    ('fix my credit', '/categories/credit-repair/'),
    ('debt relief', '/categories/debt-relief/'),
    ('best instalment loans', '/best/best-personal-loan-lenders/'),
    ('personal installment loans', '/best/best-personal-loan-lenders/'),
    ('installment lenders', '/best/best-personal-loan-lenders/'),
    ('instalment loan', '/categories/personal-loans/'),
    ('installment loans', '/categories/personal-loans/'),
    ('personal loans', '/categories/personal-loans/'),
    ('no credit check credit cards', '/best/best-no-credit-check-cards/'),
    ('no credit check cards', '/best/best-no-credit-check-cards/'),
    ('cheapest personal loans', '/best/cheapest-personal-loans/'),
    ('lowest rate personal loans', '/best/cheapest-personal-loans/'),
    ('credit repair money back guarantee', '/best/best-credit-repair-money-back-guarantee/'),
    ('credit repair for veterans', '/best/best-credit-repair-veterans/'),
    ('credit repair after bankruptcy', '/best/best-credit-repair-after-bankruptcy/'),
    ('small business loans', '/best/best-small-business-loans/'),
    ('small business loan', '/best/best-small-business-loans/'),
    ('business line of credit', '/best/best-business-lines-of-credit/'),
    ('SBA loans', '/best/best-sba-loans/'),
    ('SBA loan', '/best/best-sba-loans/'),
    ('merchant cash advance', '/best/best-merchant-cash-advance/'),
    ('equipment financing', '/best/best-equipment-financing/'),
    ('invoice factoring', '/best/best-invoice-factoring/'),
    ('startup business loans', '/best/best-startup-business-loans/'),
    ('bad credit business loans', '/best/best-bad-credit-business-loans/'),
    ('business funding', '/best/best-small-business-loans/'),
    ('working capital loan', '/best/best-small-business-loans/'),
    ('business loans', '/best/best-small-business-loans/'),
    ('business loan', '/best/best-small-business-loans/'),
    ('commercial loan', '/best/best-small-business-loans/'),
    ('SBA 7(a) loan', '/best/best-sba-loans/'),
    ('SBA 7a loan', '/best/best-sba-loans/'),
    ('MCA', '/best/best-merchant-cash-advance/'),
    ('equipment loan', '/best/best-equipment-financing/'),
    ('startup funding', '/best/best-startup-business-loans/'),
    ('startup loan', '/best/best-startup-business-loans/'),
    ('bad credit business loan', '/best/best-bad-credit-business-loans/'),
    ('accounts receivable financing', '/best/best-invoice-factoring/'),
    ('working capital', '/best/best-business-lines-of-credit/'),
    ('bridging loans', '/best/best-bridging-loans/'),
    ('bridging loan', '/best/best-bridging-loans/'),
    ('bridge loans', '/best/best-bridging-loans/'),
    ('bridge loan', '/best/best-bridging-loans/'),
    ('real estate loans', '/categories/mortgages/'),
    ('real estate loan', '/categories/mortgages/'),
    ('pawn shop loans', '/categories/pawn-shops/'),
    ('pawn shops', '/categories/pawn-shops/'),
    ('pawn shop', '/categories/pawn-shops/'),
    ('pawn loans', '/categories/pawn-shops/'),
    ('pawn broker', '/categories/pawn-shops/'),
    ('gold and jewelry', '/categories/pawn-shops/'),
    ('gold dealer', '/categories/pawn-shops/'),
    ('jewelry loan', '/categories/pawn-shops/'),
    ('chapter 7 bankruptcy', '/categories/bankruptcy/'),
    ('chapter 13 bankruptcy', '/categories/bankruptcy/'),
    ('bankruptcy attorney', '/categories/bankruptcy/'),
    ('bankruptcy filing', '/categories/bankruptcy/'),
    ('bankruptcy services', '/categories/bankruptcy/'),
    ('bankruptcy law', '/categories/bankruptcy/'),
    ('chapter 7', '/categories/bankruptcy/'),
    ('chapter 13', '/categories/bankruptcy/'),
    ('bankruptcy', '/categories/bankruptcy/'),
    ('mortgage refinance', '/categories/mortgages/'),
    ('mortgage lenders', '/categories/mortgages/'),
    ('mortgage loans', '/categories/mortgages/'),
    ('home loans', '/categories/mortgages/'),
    ('home loan', '/categories/mortgages/'),
    ('refinance', '/categories/mortgages/'),
    ('mortgage', '/categories/mortgages/'),
    ('car title loans', '/categories/emergency-cash/'),
    ('auto title loans', '/categories/emergency-cash/'),
    ('title loans', '/categories/emergency-cash/'),
    ('title loan', '/categories/emergency-cash/'),
    ('payday loans', '/best/best-payday-loan-alternatives/'),
    ('payday loan', '/best/best-payday-loan-alternatives/'),
    ('cash advance', '/best/best-cash-advance-apps/'),
    ('short-term lending', '/categories/emergency-cash/'),
    ('short-term loans', '/categories/emergency-cash/'),
    ('short term loans', '/categories/emergency-cash/'),
    ('emergency loan', '/categories/emergency-cash/'),
    ('quick cash', '/categories/emergency-cash/'),
    ('check cashing services', '/categories/check-cashing/'),
    ('check cashing', '/categories/check-cashing/'),
    ('money orders', '/categories/check-cashing/'),
    ('money order', '/categories/check-cashing/'),
    ('wire transfers', '/categories/check-cashing/'),
    ('wire transfer', '/categories/check-cashing/'),
    ('money transfer', '/categories/check-cashing/'),
    ('checking accounts', '/categories/banking/'),
    ('checking account', '/categories/banking/'),
    ('savings accounts', '/categories/banking/'),
    ('savings account', '/categories/banking/'),
    ('certificates of deposit', '/categories/banking/'),
    ('credit unions', '/categories/credit-unions/'),
    ('credit union', '/categories/credit-unions/'),
    ('used car financing', '/categories/personal-loans/'),
    ('auto loans', '/categories/personal-loans/'),
    ('auto loan', '/categories/personal-loans/'),
    ('car finance', '/categories/personal-loans/'),
    ('car loans', '/categories/personal-loans/'),
    ('car loan', '/categories/personal-loans/'),
    ('consumer complaints', '/research/consumer-complaints/'),
    ('CFPB complaints', '/research/consumer-complaints/'),
    ('CFPB data', '/research/consumer-complaints/'),
    ('complaint resolution', '/research/consumer-complaints/'),
    ('consumer protection data', '/research/consumer-complaints/'),
    ('consumer response profiles', '/trends/'),
    ('consumer response data', '/trends/'),
    ('response profiles', '/trends/'),
    ('how to build credit', '/answers/how-to-build-credit-score-fast/'),
    ('build credit with no history', '/answers/build-credit-with-no-credit-history/'),
    ('build credit from scratch', '/answers/build-credit-with-no-credit-history/'),
    ('get a personal loan', '/answers/how-to-get-a-personal-loan/'),
    ('qualify for a personal loan', '/answers/how-to-get-a-personal-loan/'),
    ('personal loan interest rates', '/answers/personal-loan-interest-rates-explained/'),
    ('how much can I borrow', '/answers/how-much-can-you-borrow-with-your-credit-score/'),
    ('credit score affects', '/answers/does-credit-score-affect-car-insurance/'),
    ('credit card interest', '/answers/how-credit-card-interest-works/'),
    ('debt consolidation yourself', '/answers/can-i-do-debt-consolidation-myself/'),
    ('do debt consolidation myself', '/answers/can-i-do-debt-consolidation-myself/'),
    ('small business loan guide', '/answers/small-business-loans-guide/'),
    ('are small business loans worth it', '/answers/are-small-business-loans-worth-it/'),
    ('find the best personal loan', '/answers/how-to-find-best-personal-loan-lenders/'),
    ('easy approval credit cards', '/answers/easy-approval-credit-cards/'),
    ('car loan with my credit score', '/answers/can-i-get-a-car-loan-with-my-credit-score/'),
    ('buy now pay later', '/categories/personal-loans/'),
    ('point-of-sale lending', '/categories/personal-loans/'),
    ('point of sale lending', '/categories/personal-loans/'),
    ('split payments', '/categories/personal-loans/'),
    ('pay over time', '/categories/personal-loans/'),
    ('deferred interest', '/about/creditdoc-data/#pricing'),
    ('soft credit check', '/answers/how-to-build-credit-score-fast/'),
    ('hard credit inquiry', '/answers/how-to-build-credit-score-fast/'),
    ('hard inquiry', '/answers/how-to-build-credit-score-fast/'),
    ('hard pull', '/answers/how-to-build-credit-score-fast/'),
    ('build credit history', '/answers/build-credit-with-no-credit-history/'),
    ('credit history', '/answers/build-credit-with-no-credit-history/'),
    ('credit scores', '/tools/credit-score-simulator/'),
    ('credit score', '/tools/credit-score-simulator/'),
    ('thin credit file', '/answers/build-credit-with-no-credit-history/'),
    ('thin credit', '/answers/build-credit-with-no-credit-history/'),
    ('no credit history', '/answers/build-credit-with-no-credit-history/'),
    ('late fees', '/about/creditdoc-data/#pricing'),
    ('hidden fees', '/about/creditdoc-data/#pricing'),
    ('annual percentage rate', '/answers/personal-loan-interest-rates-explained/'),
    ('interest rates', '/answers/personal-loan-interest-rates-explained/'),
    ('interest rate', '/answers/personal-loan-interest-rates-explained/'),
    ('credit builder', '/best/best-credit-builder-loans/'),
    ('secured card', '/best/best-secured-credit-cards/'),
    ('credit fundamentals course', '/courses/credit-fundamentals/'),
    ('free credit course', '/courses/credit-fundamentals/'),
]
