export function softenYmylCopy(text: string): string {
  return text
    .replace(/money-back guarantees/gi, 'listed refund terms')
    .replace(/money-back guarantee/gi, 'listed refund term')
    .replace(/service guarantee/gi, 'service term')
    .replace(/satisfaction guarantee/gi, 'listed satisfaction term')
    .replace(/guarantees before engaging/gi, 'terms before contacting the provider')
    .replace(/\bguarantees\b/gi, 'stated terms')
    .replace(/guaranteed results/gi, 'specific result claims')
    .replace(/guaranteed result/gi, 'specific result claim')
    .replace(/effective credit repair/gi, 'credit repair services')
    .replace(/remove negative items/gi, 'dispute reported items')
    .replace(/without overpaying/gi, 'with listed pricing context')
    .replace(/zero upfront cost to get started/gi, 'no listed setup fee')
    .replace(/comparable effectiveness/gi, 'comparable profile fields')
    .replace(/\bthe better value\b/gi, 'the lower listed-cost comparison')
    .replace(/\bbetter value\b/gi, 'stronger listed-cost context')
    .replace(/\bbetter overall value\b/gi, 'clearer listed-cost context')
    .replace(/\bstronger overall value\b/gi, 'clearer listed profile context')
    .replace(/\bclearer value proposition\b/gi, 'clearer profile context')
    .replace(/\bvalue propositions\b/gi, 'profile contexts')
    .replace(/\bvalue proposition\b/gi, 'profile context')
    .replace(/\bmore comprehensive financial platform\b/gi, 'broader listed financial feature set')
    .replace(/\bbest value\b/gi, 'lower listed-cost profile')
    .replace(/\bsuperior value\b/gi, 'stronger listed-cost context')
    .replace(/\bstronger value\b/gi, 'stronger listed-cost context')
    .replace(/\bpreferable choice\b/gi, 'profile to compare')
    .replace(/\bpreferable\b/gi, 'worth comparing')
    .replace(/\bsafer choice\b/gi, 'lower-risk profile to compare')
    .replace(/\bsafer\b/gi, 'lower-risk')
    .replace(/\bmore trustworthy option\b/gi, 'profile with more trust signals to verify')
    .replace(/\btrustworthy option\b/gi, 'profile with trust signals to verify')
    .replace(/\bmore reliable choice\b/gi, 'profile with more available trust signals')
    .replace(/\breliable choice\b/gi, 'profile with available trust signals')
    .replace(/\bclear choice\b/gi, 'clearer profile to compare')
    .replace(/\bthe better choice\b/gi, 'the clearer profile to compare')
    .replace(/\bbetter choice\b/gi, 'clearer profile to compare')
    .replace(/\bthe best choice\b/gi, 'the profile to compare')
    .replace(/\bbest choice\b/gi, 'profile to compare')
    .replace(/\bstrong choice\b/gi, 'profile with notable listed fields')
    .replace(/\bstronger choice\b/gi, 'profile with more listed fields')
    .replace(/\bbetter risk mitigation\b/gi, 'more listed risk-context fields')
    .replace(/\bbest options\b/gi, 'options to compare')
    .replace(/\bbest option\b/gi, 'option to compare')
    .replace(/\boffers the best\b/gi, 'has listed')
    .replace(/\bthe best combination\b/gi, 'a listed combination')
    .replace(/\bbest overall value\b/gi, 'notable listed-cost profile')
    .replace(/\bbest overall\b/gi, 'notable profile')
    .replace(/\bbest rates\b/gi, 'lower listed rates')
    .replace(/\bbest terms\b/gi, 'lower-cost terms')
    .replace(/\bstrongest refund policies\b/gi, 'listed refund policies')
    .replace(/\bstrongest money-back guarantee\b/gi, 'notable listed refund term')
    .replace(/\bstronger consumer protections\b/gi, 'more listed consumer-protection fields')
    .replace(/\bbetter consumer protections\b/gi, 'more listed consumer-protection fields')
    .replace(/\bsuperior consumer protections\b/gi, 'more listed consumer-protection context')
    .replace(/\bsuperior consumer protection\b/gi, 'more listed consumer-protection context')
    .replace(/\bstronger consumer protection\b/gi, 'more listed consumer-protection context')
    .replace(/\bstronger consumer safeguards\b/gi, 'more listed consumer-safeguard fields')
    .replace(/\bsignificant consumer protection\b/gi, 'listed consumer-protection field')
    .replace(/\bstronger borrower protections\b/gi, 'more listed borrower-protection fields')
    .replace(/\bbetter borrower protections\b/gi, 'more listed borrower-protection fields')
    .replace(/\benhancing borrower protection\b/gi, 'adding listed borrower-protection context')
    .replace(/\bhigher trust\b/gi, 'more trust-signal context')
    .replace(/\bstrong [A-F][+-]? BBB rating\b/gi, 'BBB rating')
    .replace(/\bstrong BBB\b/gi, 'BBB')
    .replace(/\bstrong Google reviews\b/gi, 'many Google reviews')
    .replace(/\bstronger credibility\b/gi, 'more credibility context')
    .replace(/\bsuperior credibility\b/gi, 'more credibility context')
    .replace(/\bsuperior transparency\b/gi, 'more transparency context')
    .replace(/\bsuperior reputation\b/gi, 'more public reputation signals')
    .replace(/\bdemonstrating proven customer satisfaction\b/gi, 'showing stored customer-review volume')
    .replace(/\bproven debt management results\b/gi, 'stored debt-management context')
    .replace(/\bproven results\b/gi, 'stored outcome fields')
    .replace(/\bproven track record\b/gi, 'listed track record')
    .replace(/\beliminating upfront cost risk\b/gi, 'with no listed upfront fee')
    .replace(/\bindustry gold standard\b/gi, 'commonly cited comparison point')
    .replace(/\brisk-free\b/gi, 'with published refund terms')
    .replace(/\bprotected if results do not materialize\b/gi, 'covered by the provider\'s published refund terms')
    .replace(/\bright choice\b/gi, 'option to compare')
    .replace(/\bright type of lender\b/gi, 'relevant lender category')
    .replace(/\bis better for\b/gi, 'has profile signals for')
    .replace(/\bideal for\b/gi, 'profiled for')
    .replace(/\bChoose ([^.;]+?) for\b/g, 'Compare $1 for')
    .replace(/\bchoose ([^.;]+?) for\b/g, 'compare $1 for')
    .replace(/\btop companies compared\b/gi, 'company profiles compared')
    .replace(/\btop-rated credit repair companies\b/gi, 'credit repair company profiles')
    .replace(/\btop-rated\b/gi, 'profiled')
    .replace(/\btop-ranked local lenders\b/gi, 'local lender profiles')
    .replace(/\btop-ranked\b/gi, 'profiled')
    .replace(/\bfull rankings & reviews\b/gi, 'provider profiles and comparisons')
    .replace(/\bCompare the Best\b/gi, 'Compare')
    .replace(/\bbest for\b/gi, 'profile signals for')
    .replace(/\bBest For\b/g, 'Profile Signals')
    .replace(/\bNOT recommended for consumers seeking\b/g, 'Flagged for caution for consumers researching')
    .replace(/\bnot recommended for consumers seeking\b/gi, 'flagged for caution for consumers researching')
    .replace(/\brecommended for consumers seeking\b/gi, 'profiled for consumers researching')
    .replace(/\brecommended for\b/gi, 'profiled for')
    .replace(/\bprofessional recommendations\b/gi, 'professional referrals')
    .replace(/\btop lenders\b/gi, 'listed lenders')
    .replace(/\btop personal loan lenders\b/gi, 'personal loan lender profiles')
    .replace(/\btop secured cards\b/gi, 'secured card profiles')
    .replace(/\bSee Top 5\b/gi, 'See')
    .replace(/\bget matched with lenders\b/gi, 'review lender options')
    .replace(/\bget matched\b/gi, 'review options')
    .replace(/\bmatched provider profiles\b/gi, 'provider profiles shown')
    .replace(/\bactually approve borrowers\b/gi, 'publish eligibility fields')
    .replace(/\bapproval odds\b/gi, 'eligibility fields')
    .replace(/\bwins\b/gi, 'is flagged')
    .replace(/Our editorial team independently evaluates all services\. Compensation does not influence editorial reviews, page order, or recommendations;/gi, 'Compensation does not determine whether a provider can be covered or how visible star ratings are calculated;')
    .replace(/Compensation does not influence editorial reviews, page order, or recommendations;/gi, 'Compensation does not determine whether a provider can be covered or how visible star ratings are calculated;');
}
