export function softenYmylCopy(text: string): string {
  return text
    .replace(/money-back guarantees/gi, 'listed refund terms')
    .replace(/money-back guarantee/gi, 'listed refund term')
    .replace(/service guarantee/gi, 'service term')
    .replace(/satisfaction guarantee/gi, 'listed satisfaction term')
    .replace(/guarantees before engaging/gi, 'terms before contacting the provider')
    .replace(/\bguarantees\b/gi, 'stated terms')
    .replace(/guaranteed results/gi, 'specific result claims')
    .replace(/guaranteed result/gi, 'specific result claim')
    .replace(/effective credit repair/gi, 'credit repair services')
    .replace(/remove negative items/gi, 'dispute reported items')
    .replace(/without overpaying/gi, 'with listed pricing context')
    .replace(/zero upfront cost to get started/gi, 'no listed setup fee')
    .replace(/comparable effectiveness/gi, 'comparable profile fields')
    .replace(/\bthe better value\b/gi, 'the lower listed-cost comparison')
    .replace(/\bbetter value\b/gi, 'stronger listed-cost context')
    .replace(/\bbetter overall value\b/gi, 'clearer listed-cost context')
    .replace(/\bstronger overall value\b/gi, 'clearer listed profile context')
    .replace(/\bclearer value proposition\b/gi, 'clearer profile context')
    .replace(/\bvalue propositions\b/gi, 'profile contexts')
    .replace(/\bvalue proposition\b/gi, 'profile context')
    .replace(/\bmore comprehensive financial platform\b/gi, 'broader listed financial feature set')
    .replace(/\bbest value\b/gi, 'lower listed-cost profile')
    .replace(/\bsuperior value\b/gi, 'stronger listed-cost context')
    .replace(/\bstronger value\b/gi, 'stronger listed-cost context')
    .replace(/\bpreferable choice\b/gi, 'profile to compare')
    .replace(/\bpreferable\b/gi, 'worth comparing')
    .replace(/\bsafer choice\b/gi, 'lower-risk profile to compare')
    .replace(/\bsafer\b/gi, 'lower-risk')
    .replace(/\bmore trustworthy option\b/gi, 'profile with more trust signals to verify')
    .replace(/\btrustworthy option\b/gi, 'profile with trust signals to verify')
    .replace(/\bmore reliable choice\b/gi, 'profile with more available trust signals')
    .replace(/\breliable choice\b/gi, 'profile with available trust signals')
    .replace(/\bclear choice\b/gi, 'clearer profile to compare')
    .replace(/\bthe better choice\b/gi, 'the clearer profile to compare')
    .replace(/\bbetter choice\b/gi, 'clearer profile to compare')
    .replace(/\bthe best choice\b/gi, 'the profile to compare')
    .replace(/\bbest choice\b/gi, 'profile to compare')
    .replace(/\bstrong choice\b/gi, 'profile with notable listed fields')
    .replace(/\bstronger choice\b/gi, 'profile with more listed fields')
    .replace(/\bbetter risk mitigation\b/gi, 'more listed risk-context fields')
    .replace(/\bbest options\b/gi, 'options to compare')
    .replace(/\bbest option\b/gi, 'option to compare')
    .replace(/\boffers the best\b/gi, 'has listed')
    .replace(/\bthe best combination\b/gi, 'a listed combination')
    .replace(/\bbest overall value\b/gi, 'notable listed-cost profile')
    .replace(/\bbest overall\b/gi, 'notable profile')
    .replace(/\bbest rates\b/gi, 'lower listed rates')
    .replace(/\bbest terms\b/gi, 'lower-cost terms')
    .replace(/\bstrongest refund policies\b/gi, 'listed refund policies')
    .replace(/\bstrongest money-back guarantee\b/gi, 'notable listed refund term')
    .replace(/\bstronger consumer protections\b/gi, 'more listed consumer-protection fields')
    .replace(/\bbetter consumer protections\b/gi, 'more listed consumer-protection fields')
    .replace(/\bsuperior consumer protections\b/gi, 'more listed consumer-protection context')
    .replace(/\bsuperior consumer protection\b/gi, 'more listed consumer-protection context')
    .replace(/\bstronger consumer protection\b/gi, 'more listed consumer-protection context')
    .replace(/\bstronger consumer safeguards\b/gi, 'more listed consumer-safeguard fields')
    .replace(/\bsignificant consumer protection\b/gi, 'listed consumer-protection field')
    .replace(/\bstronger borrower protections\b/gi, 'more listed borrower-protection fields')
    .replace(/\bbetter borrower protections\b/gi, 'more listed borrower-protection fields')
    .replace(/\benhancing borrower protection\b/gi, 'adding listed borrower-protection context')
    .replace(/\bhigher trust\b/gi, 'more trust-signal context')
    .replace(/\bstrong [A-F][+-]? BBB rating\b/gi, 'BBB rating')
    .replace(/\bstrong BBB\b/gi, 'BBB')
    .replace(/\bstrong Google reviews\b/gi, 'many Google reviews')
    .replace(/\bstronger credibility\b/gi, 'more credibility context')
    .replace(/\bsuperior credibility\b/gi, 'more credibility context')
    .replace(/\bsuperior transparency\b/gi, 'more transparency context')
    .replace(/\bsuperior reputation\b/gi, 'more public reputation signals')
    .replace(/\bdemonstrating proven customer satisfaction\b/gi, 'showing stored customer-review volume')
    .replace(/\bproven debt management results\b/gi, 'stored debt-management context')
    .replace(/\bproven results\b/gi, 'stored outcome fields')
    .replace(/\bproven track record\b/gi, 'listed track record')
    .replace(/\beliminating upfront cost risk\b/gi, 'with no listed upfront fee')
    .replace(/\bindustry gold standard\b/gi, 'commonly cited comparison point')
    .replace(/\brisk-free\b/gi, 'with published refund terms')
    .replace(/\bprotected if results do not materialize\b/gi, 'covered by the provider\'s published refund terms')
    .replace(/\bright choice\b/gi, 'option to compare')
    .replace(/\bright type of lender\b/gi, 'relevant lender category')
    .replace(/\bis better for\b/gi, 'has profile signals for')
    .replace(/\bideal for\b/gi, 'profiled for')
    .replace(/\bChoose ([^.;]+?) only if\b/g, 'Compare $1 only when')
    .replace(/\bchoose ([^.;]+?) only if\b/g, 'compare $1 only when')
    .replace(/\bChoose ([^.;]+?) for\b/g, 'Compare $1 for')
    .replace(/\bchoose ([^.;]+?) for\b/g, 'compare $1 for')
    .replace(/\bConsumers should choose\b/gi, 'Consumers can compare')
    .replace(/\bshould choose\b/gi, 'can compare')
    .replace(/\bthe superior choice\b/gi, 'the profile with more listed fields')
    .replace(/\bsuperior choice\b/gi, 'profile with more listed fields')
    .replace(/\btop companies compared\b/gi, 'company profiles compared')
    .replace(/\btop-rated credit repair companies\b/gi, 'credit repair company profiles')
    .replace(/\btop-rated\b/gi, 'profiled')
    .replace(/\btop-ranked local lenders\b/gi, 'local lender profiles')
    .replace(/\btop-ranked\b/gi, 'profiled')
    .replace(/\bfull rankings & reviews\b/gi, 'provider profiles and comparisons')
    .replace(/\bCompare the Best\b/gi, 'Compare')
    .replace(/\bbest for\b/gi, 'profile signals for')
    .replace(/\bBest For\b/g, 'Profile Signals')
    .replace(/\bNOT recommended for consumers seeking\b/g, 'Flagged for caution for consumers researching')
    .replace(/\bnot recommended for consumers seeking\b/gi, 'flagged for caution for consumers researching')
    .replace(/\brecommended for consumers seeking\b/gi, 'profiled for consumers researching')
    .replace(/\brecommended for\b/gi, 'profiled for')
    .replace(/\bprofessional recommendations\b/gi, 'professional referrals')
    .replace(/\btop lenders\b/gi, 'listed lenders')
    .replace(/\btop personal loan lenders\b/gi, 'personal loan lender profiles')
    .replace(/\btop secured cards\b/gi, 'secured card profiles')
    .replace(/\bSee Top 5\b/gi, 'See')
    .replace(/\bget matched with lenders\b/gi, 'review lender options')
    .replace(/\bget matched\b/gi, 'review options')
    .replace(/\bmatched provider profiles\b/gi, 'provider profiles shown')
    .replace(/\bactually approve borrowers\b/gi, 'publish eligibility fields')
    .replace(/\bapproval odds\b/gi, 'eligibility fields')
    .replace(/\bquick wins\b/gi, 'quick progress markers')
    .replace(/\bwins\b/gi, 'results')
    .replace(/Our editorial team independently evaluates all services\. Compensation does not influence editorial reviews, page order, or recommendations;/gi, 'Compensation does not determine whether a provider can be covered or how visible star ratings are calculated;')
    .replace(/Compensation does not influence editorial reviews, page order, or recommendations;/gi, 'Compensation does not determine whether a provider can be covered or how visible star ratings are calculated;');
}

export function softenEducationalTeaserCopy(text: string): string {
  return softenYmylCopy(text)
    .replace(/^Best\b/i, 'Compare')
    .replace(/\bBest Free\b/g, 'Compare Free')
    .replace(/\bBest\b/g, 'Compare')
    .replace(/\bGuaranteed Approval\b/g, 'Advertised Approval Claims')
    .replace(/\bguaranteed approval\b/gi, 'advertised approval claims')
    .replace(/\badvertised approval claims personal loans\b/gi, 'advertised approval claims for personal loans')
    .replace(/\badvertised approval claims credit cards\b/gi, 'advertised approval claims for credit cards')
    .replace(/\bstated terms approval\b/gi, 'advertises certain approval')
    .replace(/\bHere'?s Eligibility Fields to Check\b/gi, 'Here are eligibility fields to check')
    .replace(/\bWho Actually Approves\b/gi, 'Eligibility Fields to Check')
    .replace(/\bWho Approves\b/gi, 'Eligibility Fields to Check')
    .replace(/\bHere'?s Eligibility Fields to Check\b/gi, 'Here are eligibility fields to check')
    .replace(/\bwhat lenders actually check\b/gi, 'what lenders commonly check')
    .replace(/\bwhich lenders approve ([^.]+?) in\b/gi, 'which lenders publish eligibility fields for $1 in')
    .replace(/\bwhich lenders approve\b/gi, 'which lenders publish eligibility fields')
    .replace(/\bwhich cards have the highest acceptance rates\b/gi, 'which cards publish eligibility signals')
    .replace(/\bhighest acceptance rates\b/gi, 'published eligibility signals')
    .replace(/\bCan you get a personal loan with a 500 credit score\? Yes\b/gi, 'Is a personal loan possible with a 500 credit score? It can be')
    .replace(/\bWhat You Need to Know\b/gi, 'Key Context')
    .replace(/\bWhat Credit Score Do You Need to Buy a House in (\d{4})\?/gi, 'Credit Score Context for Buying a House in $1')
    .replace(/\bwhat you need to know\b/gi, 'key context')
    .replace(/\bwhat you need before\b/gi, 'context before')
    .replace(/\bwhat you need\b/gi, 'key context')
    .replace(/\bKey Context before\b/g, 'key context before')
    .replace(/\byou should use it\b/gi, 'it is worth evaluating')
    .replace(/\byou should use\b/gi, 'it can be useful to evaluate')
    .replace(/\bhow to choose\b/gi, 'how to compare')
    .replace(/\bEasy Approval\b/gi, 'Simplified Approval Claims')
    .replace(/\bHow to Get Approved\b/gi, 'Eligibility Fields to Check')
    .replace(/\bHow to Qualify for\b/gi, 'Eligibility Fields for')
    .replace(/\bHow to Qualify\b/gi, 'Eligibility Fields to Check')
    .replace(/\bBetter Loan Deal\b/gi, 'Loan Cost Comparison')
    .replace(/\bWhich Protects You Better\?/gi, 'Protection Trade-Offs')
    .replace(/\bWhat Hurts Your Score\?/gi, 'Credit-Score Impact')
    .replace(/\bWhere to Apply and What to Expect\b/gi, 'Application Context and What to Expect')
    .replace(/\bShould You Get a Cosigner\?/gi, 'Cosigner Trade-Offs')
    .replace(/\bYou Should Try First\b/gi, 'to Review First')
    .replace(/\bWhich Payoff Method Works Faster\?/gi, 'Payoff Method Trade-Offs')
    .replace(/\bWhich Should You Choose\?/gi, 'Trade-Offs to Compare')
    .replace(/\bWhat You Actually Need\b/gi, 'Account Trade-Offs to Compare')
    .replace(/\bHow to Stop It and Protect\b/gi, 'Response Steps and Ways to Protect')
    .replace(/\bWhich You Need\b/gi, 'Trade-Offs to Compare')
    .replace(/\bFinancial Safety\b/gi, 'Financial Account Protection')
    .replace(/\bCosigner Trade-Offs Risks\b/gi, 'Cosigner Trade-Offs: Risks')
    .replace(/\bWhere to Get a Loan Cost Comparison\b/gi, 'Loan Cost Comparison')
    .replace(/\bEligibility Fields to Check with listed pricing context\b/gi, 'Eligibility Fields and Listed Pricing Context')
    .replace(/\bWhich Protection Is worth evaluating\?/gi, 'Protection Trade-Offs')
    .replace(/\bIs It worth evaluating for\b/gi, 'How to Evaluate')
    .replace(/\bWhich Is Right for You\?/gi, 'Costs and Trade-Offs')
    .replace(/\bWhich Is Right for You\b/gi, 'Costs and Trade-Offs')
    .replace(/\bWhich Is worth evaluating\?/gi, 'Costs and Trade-Offs')
    .replace(/\bWhich Is worth evaluating\b/gi, 'Costs and Trade-Offs')
    .replace(/\bAre ([^?]+?) a Good Choice for Your Goals\?/gi, 'How to Evaluate $1 for Your Goals')
    .replace(/\bAre ([^?]+?) a Good Idea\?/gi, 'How to Evaluate $1')
    .replace(/\bAre ([^?]+?) Worth It in (\d{4})\?/gi, 'How to Evaluate $1 in $2')
    .replace(/\bIs ([^?]+?) Worth It in (\d{4})\?/gi, 'How to Evaluate $1 in $2')
    .replace(/\bAre ([^?]+?) Worth It\?/gi, 'How to Evaluate $1')
    .replace(/\bIs ([^?]+?) Worth It\?/gi, 'How to Evaluate $1')
    .replace(/\bAre ([^?]+?) Bad for Your Credit\?/gi, 'How $1 Can Affect Credit')
    .replace(/\bAre ([^?]+?) Bad\?/gi, 'How $1 Can Affect Credit')
    .replace(/\bAre ([^?]+?) Good\?/gi, 'How $1 Can Work')
    .replace(/\bwhether they(?:'re| are) right for you\b/gi, 'how to evaluate them')
    .replace(/\bif they(?:'re| are) right for you\b/gi, 'how to evaluate them')
    .replace(/\bwhether (it|this strategy|this product|this option) is right for you\b/gi, 'how to evaluate $1')
    .replace(/\bif (it|this strategy|this product|this option) is right for you\b/gi, 'how to evaluate $1')
    .replace(/\bright for your situation\b/gi, 'relevant to your situation')
    .replace(/\bright for you\b/gi, 'worth evaluating')
    .replace(/\bthe right move\b/gi, 'an option to evaluate')
    .replace(/\bbad for your credit\b/gi, 'a credit-impact question')
    .replace(/\bThe Truth in 2026\b/gi, 'What to Know in 2026')
    .replace(/\b2026 Truth\b/gi, '2026 Context')
    .replace(/\bThe Truth\b/gi, 'What to Know')
    .replace(/\bthe Truth\b/g, 'what to know')
    .replace(/\bWorth It\?/gi, 'Evaluation Guide')
    .replace(/\bworth it\b/gi, 'worth evaluating')
    .replace(/\bWhich Protection Is worth evaluating\?/gi, 'Protection Trade-Offs')
    .replace(/\bIs It worth evaluating for\b/gi, 'How to Evaluate')
    .replace(/\bHow to Evaluate Your Financial Account Protection\?/gi, 'Financial Account Protection Evaluation Guide')
    .replace(/\bworth the benefit\b/gi, 'a trade-off to evaluate')
    .replace(/\bhelp you decide\b/gi, 'help you compare')
    .replace(/\bdecide if\b/gi, 'compare whether')
    .replace(/\bfastest ways\b/gi, 'common routes')
    .replace(/\bwork best\b/gi, 'are commonly used')
    .replace(/\bfastest way\b/gi, 'one route')
    .replace(/\bfastest path\b/gi, 'one path')
    .replace(/\bcheapest option\b/gi, 'lower-cost option')
    .replace(/\bcheapest source\b/gi, 'lower-cost source')
    .replace(/\bboosting scores\b/gi, 'score-change context')
    .replace(/\bimprove your score\b/gi, 'support score improvement context')
    .replace(/\bimproves your financial future\b/gi, 'supports your financial planning');
}

export function softenGlossaryCopy(text: string): string {
  return softenEducationalTeaserCopy(text)
    .replace(/\bYou should check all three reports\b/gi, 'It can be useful to check all three reports')
    .replace(/\bthe strongest protection against identity theft\b/gi, 'one of the strongest consumer protections against identity theft')
    .replace(/\bshopping around is safe\b/gi, 'comparison shopping can be done without a score impact')
    .replace(/\byou must pay off the balance\b/gi, 'payoff before the promotional period ends matters')
    .replace(/\bThe smallest amount you must pay each month\b/gi, 'The smallest listed amount required each month')
    .replace(/\bBureaus must investigate within 30 days and remove inaccurate information\b/gi, 'Bureaus generally have investigation obligations and must address inaccurate information')
    .replace(/\bthey must remove it\b/gi, 'they generally have to remove it')
    .replace(/\bmust stop contacting you\b/gi, 'is required to stop contacting you')
    .replace(/\byou can sue\b/gi, 'you may have a right to sue')
    .replace(/\bEvery lender must show costs the same way\b/gi, 'Lenders are required to show costs in comparable ways')
    .replace(/\bthe best deal\b/gi, 'a lower-cost offer')
    .replace(/\byou might only need to repay\b/gi, 'you may only be required to repay')
    .replace(/\byou must pay Mortgage Insurance Premium\b/gi, 'borrowers pay Mortgage Insurance Premium')
    .replace(/\byou need to stay long enough to break even\b/gi, 'the break-even period matters')
    .replace(/\bLenders must show APR by law\b/gi, 'Lenders are required to show APR by law')
    .replace(/\bThe lender must disclose this number under What to Know in Lending Act\b/gi, 'The lender is required to disclose this number under the Truth in Lending Act')
    .replace(/\bIncome must be below your state'?s median to qualify\b/gi, 'Eligibility often depends on income being below your state median')
    .replace(/\bremove all negative items guaranteed\b/gi, 'promise removal of all negative items')
    .replace(/\bmust address inaccurate information\. you may have a right to sue\b/gi, 'are required to address inaccurate information. You may have a right to sue')
    .replace(/\bboth must show APR\b/gi, 'both are required to show APR')
    .replace(/\bmortgage guaranteed by the Department of Veterans Affairs\b/gi, 'mortgage backed by the Department of Veterans Affairs')
    .replace(/\bmost reliable way to find the cheapest loan\b/gi, 'one way to compare loan cost')
    .replace(/\bthe cheapest loan\b/gi, 'a lower-cost loan')
    .replace(/\bcheapest loan\b/gi, 'lower-cost loan')
    .replace(/\bChapter 13 is better than Chapter 7\b/gi, 'Chapter 13 may be more relevant than Chapter 7')
    .replace(/\bLower LTV = lower risk for lender = better rate for you\b/gi, 'Lower LTV can mean lower lender risk and different rate context')
    .replace(/\bbest mortgage deals available\b/gi, 'mortgage options with notable listed benefits');
}
